name = "NeighborhoodApproximationIndex"
uuid = "73dc1408-15d9-420f-8382-2ac46fb81e72"
authors = ["Eric S. Tellez"]
version = "0.1.0"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
